# Site settings
title: Arena Jornalismo Esportivo
description: |
  Curso de extensão em Jornalismo Esportivo<br>
  voltado para o mercado de trabalho -<br>
  seja na TV, no impresso ou nas assessorias

owner: Arena Jornalismo Esportivo # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: arenajornalismoesportivo@gmail.com
baseurl: "http://arenajornalismoesportivo.com.br" # the subpath of your site, e.g. /blog
url: "http://arenajornalismoesportivo.com.br" #
social:
  facebook-official: https://facebook.com/arenajornalismoesportivo
  email: arenajornalismoesportivo@gmail.com
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
